FROM nvidia/cudagl:11.3.1-devel-ubuntu20.04

#############################################
# SECTION 0: Install cuDNN                  #
#############################################
ENV NV_CUDNN_VERSION=8.2.0.53

ENV NV_CUDNN_PACKAGE="libcudnn8=$NV_CUDNN_VERSION-1+cuda11.3" \
    NV_CUDNN_PACKAGE_DEV="libcudnn8-dev=$NV_CUDNN_VERSION-1+cuda11.3" \
    NV_CUDNN_PACKAGE_NAME="libcudnn8"

RUN apt-get update && apt-get install -y --no-install-recommends \
    ${NV_CUDNN_PACKAGE} \
    ${NV_CUDNN_PACKAGE_DEV} \
  && apt-mark hold ${NV_CUDNN_PACKAGE_NAME} \
  && rm -rf /var/lib/apt/lists/*

#########################################
# SECTION 1: Essentials                 #
#########################################
# Run apt-get (dkpg) without interactive dialogue
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    vim git curl wget yasm cmake unzip pkg-config \
    checkinstall build-essential ca-certificates \
    software-properties-common apt-utils bash-completion \
    libeigen3-dev \
  && apt-get upgrade -y \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Setup locale language config
RUN apt-get update && apt-get install -y --no-install-recommends locales \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \
  && locale-gen "en_US.UTF-8" \
  && update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 \
  && ln -fs /usr/share/zoneinfo/America/Los_Angeles /etc/localtime  # Set timezone
ENV LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8

#########################################
# SECTION 1.5: Install ROS noetic       #
#########################################
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list' \
  && curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add - \
  && apt-get update && apt-get install -y ros-noetic-desktop \
  && apt-get install -y python3-rosdep \
  && rosdep init && rosdep update \
  && apt-get install -y python3-rosinstall python3-rosinstall-generator \
     python3-wstool ros-noetic-catkin \
  && echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

ENV ROS_DISTRO noetic

#########################################
# SECTION 2: Setup Image Libraries      #
#########################################
RUN apt-get update && apt-get install -y --no-install-recommends \
    zlib1g-dev libjpeg-dev libpng-dev xvfb ffmpeg xorg-dev \
    xorg-dev libboost-all-dev libsdl2-dev swig \
    libblas-dev liblapack-dev \
    libopenblas-base libatlas-base-dev graphviz \
  && apt-get upgrade -y \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

#########################################
# SECTION 3: Install Python Libraries   #
#########################################
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \
  && python3 -m pip install --upgrade pip \
  && python3 -m pip install jupyter jupyter_contrib_nbextensions \
  && jupyter contrib nbextension install \
  && python3 -m pip install jupyter_nbextensions_configurator \
  && jupyter nbextensions_configurator enable \
  && jupyter nbextension enable codefolding/main \
  && mkdir /.local && chmod a+rwx /.local

# Install Python dependencies
COPY scene_recon/requirements.txt /tmp/
# Update PyYAML for uninstalling distutils packages issue
RUN python3 -m pip install -I PyYAML \
  && python3 -m pip install -r /tmp/requirements.txt \
  && rm -r /tmp/*

######################################
# SECTION 5: Add running instruction #
######################################
# Set working directory to be repository directory
ENV REPOPATH /maya-slam
WORKDIR ${REPOPATH}

# Append the custom bashrc
COPY bashrc /tmp/
RUN cat /tmp/bashrc > /etc/bash.bashrc

# For CUDA library
ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64:${LD_LIBRARY_PATH}
# Tensorflow 2.4.1 CUDA library issue
RUN ln -s /usr/local/cuda-11.3/lib64/libcusolver.so.11 /usr/local/cuda-11.3/lib64/libcusolver.so.10

#######################################
# SECTION 6: Additional installations #
#######################################


#######################################
# SECTION 7: Helpful commands         #
#######################################
#ENV COMMANDTOCOMPILE="cd slam_algorithms/ORB_SLAM3 && ./build.sh && ./build_ros.sh"
ENV JUPYTERPORT="9001"
ENV COMMANDTORUNJUPYTER="jupyter notebook --no-browser --ip=0.0.0.0 --allow-root --port=${JUPYTERPORT} &"
