bags:
  - 1:
    name: h_e_1.bag
    bag_path: /home/ffurrer/Desktop/
    intrinsics_path: /home/ffurrer/hand_eye_ws/src/hand_eye_calibration/hand_eye_calibration/calib/
    target_config_path: /home/ffurrer/hand_eye_ws/src/hand_eye_calibration/hand_eye_calibration/calib/
    cameras:
      cam_topics:
        - /camera/rgb/image_raw
      cam_intrinsics:
        - primesense_rgb.yaml
    target: target_83_249.yaml
    tf_frames:
      source:
        - primesense
      target:
        - optitrack
  - 2:
    name: h_e_2.bag
    bag_path: /home/ffurrer/Desktop/
    intrinsics_path: /home/ffurrer/hand_eye_ws/src/hand_eye_calibration/hand_eye_calibration/calib/
    target_config_path: /home/ffurrer/hand_eye_ws/src/hand_eye_calibration/hand_eye_calibration/calib/
    cameras:
      cam_topics:
        - /camera/rgb/image_raw
      cam_intrinsics:
        - primesense_rgb.yaml
    target: target_83_249.yaml
    tf_frames:
      source:
        - primesense
      target:
        - optitrack
  - 3:
    name: h_e_3.bag
    bag_path: /home/ffurrer/Desktop/
    intrinsics_path: /home/ffurrer/hand_eye_ws/src/hand_eye_calibration/hand_eye_calibration/calib/
    target_config_path: /home/ffurrer/hand_eye_ws/src/hand_eye_calibration/hand_eye_calibration/calib/
    cameras:
      cam_topics:
        - /camera/rgb/image_raw
      cam_intrinsics:
        - primesense_rgb.yaml
    target: target_83_249.yaml
    tf_frames:
      source:
        - primesense
      target:
        - optitrack
  - 4:
    name: h_e_4.bag
    bag_path: /home/ffurrer/Desktop/
    intrinsics_path: /home/ffurrer/hand_eye_ws/src/hand_eye_calibration/hand_eye_calibration/calib/
    target_config_path: /home/ffurrer/hand_eye_ws/src/hand_eye_calibration/hand_eye_calibration/calib/
    cameras:
      cam_topics:
        - /camera/rgb/image_raw
      cam_intrinsics:
        - primesense_rgb.yaml
    target: target_83_249.yaml
    tf_frames:
      source:
        - primesense
      target:
        - optitrack
  - 5:
    name: h_e_5.bag
    bag_path: /home/ffurrer/Desktop/
    intrinsics_path: /home/ffurrer/hand_eye_ws/src/hand_eye_calibration/hand_eye_calibration/calib/
    target_config_path: /home/ffurrer/hand_eye_ws/src/hand_eye_calibration/hand_eye_calibration/calib/
    cameras:
      cam_topics:
        - /camera/rgb/image_raw
      cam_intrinsics:
        - primesense_rgb.yaml
    target: target_55_165.yaml
    tf_frames:
      source:
        - primesense
      target:
        - optitrack
  - 6:
    name: h_e_6.bag
    bag_path: /home/ffurrer/Desktop/
    intrinsics_path: /home/ffurrer/hand_eye_ws/src/hand_eye_calibration/hand_eye_calibration/calib/
    target_config_path: /home/ffurrer/hand_eye_ws/src/hand_eye_calibration/hand_eye_calibration/calib/
    cameras:
      cam_topics:
        - /camera/rgb/image_raw
      cam_intrinsics:
        - primesense_rgb.yaml
    target: target_55_165.yaml
    tf_frames:
      source:
        - primesense
      target:
        - optitrack
  - 7:
    name: h_e_7.bag
    bag_path: /home/ffurrer/Desktop/
    intrinsics_path: /home/ffurrer/hand_eye_ws/src/hand_eye_calibration/hand_eye_calibration/calib/
    target_config_path: /home/ffurrer/hand_eye_ws/src/hand_eye_calibration/hand_eye_calibration/calib/
    cameras:
      cam_topics:
        - /camera/rgb/image_raw
      cam_intrinsics:
        - primesense_rgb.yaml
    target: target_55_165.yaml
    tf_frames:
      source:
        - primesense
      target:
        - optitrack
